/*
 * TextBlockUI.java
 *
 * Created on 10. Dezember 2005, 15:10
 */

package ecobill.module.base.ui.textblock;

/**
 *
 * @author  Roman Georg Rädle
 */
public class TextBlockUI extends javax.swing.JFrame {
    
    /** Creates new form TextBlockUI */
    public TextBlockUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        textBlockPanel = new javax.swing.JPanel();
        articleTable1 = new ecobill.module.base.ui.article.ArticleTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        input1 = new ecobill.module.base.ui.textblock.Input();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Schlie\u00dfen");

        jButton2.setText("Einf\u00fcgen");

        org.jdesktop.layout.GroupLayout textBlockPanelLayout = new org.jdesktop.layout.GroupLayout(textBlockPanel);
        textBlockPanel.setLayout(textBlockPanelLayout);
        textBlockPanelLayout.setHorizontalGroup(
            textBlockPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, textBlockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(textBlockPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, textBlockPanelLayout.createSequentialGroup()
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1))
                    .add(articleTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(input1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                .addContainerGap())
        );

        textBlockPanelLayout.linkSize(new java.awt.Component[] {jButton1, jButton2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        textBlockPanelLayout.setVerticalGroup(
            textBlockPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, textBlockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(input1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(articleTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textBlockPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap())
        );
        getContentPane().add(textBlockPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextBlockUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ecobill.module.base.ui.article.ArticleTable articleTable1;
    private ecobill.module.base.ui.textblock.Input input1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel textBlockPanel;
    // End of variables declaration//GEN-END:variables
    
}
