# MySQL-Front 3.2  (Build 4.15)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET CHARACTER SET 'utf8' */;

# Host: localhost    Database: ecobill
# ------------------------------------------------------
# Server version 4.1.11-nt

USE `ecobill`;

#
# Dumping data for table base_delivery_order
#

INSERT INTO `base_delivery_order` (`ID`,`BUSINESS_PARTNER_ID`,`DELIVERY_ORDER_NUMBER`,`DELIVERY_ORDER_DATE`,`CHARACTERISATION_TYPE`,`PREPARED_BILL`,`BILL_ID`) VALUES (1,1,2,'2005-07-28','DELIVERY_ORDER',1,1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
