# MySQL-Front 3.2  (Build 4.15)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET CHARACTER SET 'utf8' */;

# Host: localhost    Database: org.ecobill
# ------------------------------------------------------
# Server version 4.1.11-nt

USE `org.ecobill`;

#
# Dumping data for table base_bill
#

INSERT INTO `base_bill` (`ID`,`BUSINESS_PARTNER_ID`,`BILL_NUMBER`,`BILL_DATE`) VALUES (1,1,9876,'2005-07-30');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
