/*
 * ArticleUI.java
 *
 * Created on 28. September 2005, 16:57
 */

package ecobill.module.base.ui.article;

/**
 *
 * @author  Roman Georg Rädle
 */
public class ArticleUI extends javax.swing.JPanel {
    
    /** Creates new form ArticleUI */
    public ArticleUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tabbedPane = new javax.swing.JTabbedPane();
        overview = new javax.swing.JPanel();
        verticalButtonOverview = new ecobill.module.base.ui.article.VerticalButton();
        inputOverview = new ecobill.module.base.ui.article.Input();
        inputBundleOverview = new ecobill.module.base.ui.article.InputBundle();
        descriptionOverview = new ecobill.module.base.ui.article.Description();
        descriptionTableOverview = new ecobill.module.base.ui.article.DescriptionTable();
        articleTableOverview = new ecobill.module.base.ui.article.ArticleTable();
        labelling = new javax.swing.JPanel();
        verticalButtonLabelling = new ecobill.module.base.ui.article.VerticalButton();
        inputDescriptionLabelling = new ecobill.module.base.ui.article.InputDescription();
        descriptionLabelling = new ecobill.module.base.ui.article.Description();
        descriptionTableLabelling = new ecobill.module.base.ui.article.DescriptionTable();

        setLayout(new java.awt.BorderLayout());

        org.jdesktop.layout.GroupLayout overviewLayout = new org.jdesktop.layout.GroupLayout(overview);
        overview.setLayout(overviewLayout);
        overviewLayout.setHorizontalGroup(
            overviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(overviewLayout.createSequentialGroup()
                .addContainerGap()
                .add(overviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(articleTableOverview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .add(overviewLayout.createSequentialGroup()
                        .add(verticalButtonOverview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(overviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(overviewLayout.createSequentialGroup()
                                .add(inputOverview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(inputBundleOverview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(descriptionOverview, 0, 0, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(descriptionTableOverview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        overviewLayout.setVerticalGroup(
            overviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(overviewLayout.createSequentialGroup()
                .addContainerGap()
                .add(overviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, descriptionTableOverview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(verticalButtonOverview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, overviewLayout.createSequentialGroup()
                        .add(overviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, inputBundleOverview, 0, 0, Short.MAX_VALUE)
                            .add(inputOverview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(descriptionOverview, 0, 166, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(articleTableOverview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabbedPane.addTab("\u00dcbersicht", overview);

        org.jdesktop.layout.GroupLayout labellingLayout = new org.jdesktop.layout.GroupLayout(labelling);
        labelling.setLayout(labellingLayout);
        labellingLayout.setHorizontalGroup(
            labellingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(labellingLayout.createSequentialGroup()
                .addContainerGap()
                .add(labellingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(descriptionTableLabelling, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .add(labellingLayout.createSequentialGroup()
                        .add(verticalButtonLabelling, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(inputDescriptionLabelling, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(descriptionLabelling, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
                .addContainerGap())
        );
        labellingLayout.setVerticalGroup(
            labellingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(labellingLayout.createSequentialGroup()
                .addContainerGap()
                .add(labellingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, descriptionLabelling, 0, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, inputDescriptionLabelling, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(verticalButtonLabelling, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(descriptionTableLabelling, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabbedPane.addTab("Bezeichnungen", labelling);

        add(tabbedPane, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ecobill.module.base.ui.article.ArticleTable articleTableOverview;
    private ecobill.module.base.ui.article.Description descriptionLabelling;
    private ecobill.module.base.ui.article.Description descriptionOverview;
    private ecobill.module.base.ui.article.DescriptionTable descriptionTableLabelling;
    private ecobill.module.base.ui.article.DescriptionTable descriptionTableOverview;
    private ecobill.module.base.ui.article.InputBundle inputBundleOverview;
    private ecobill.module.base.ui.article.InputDescription inputDescriptionLabelling;
    private ecobill.module.base.ui.article.Input inputOverview;
    private javax.swing.JPanel labelling;
    private javax.swing.JPanel overview;
    private javax.swing.JTabbedPane tabbedPane;
    private ecobill.module.base.ui.article.VerticalButton verticalButtonLabelling;
    private ecobill.module.base.ui.article.VerticalButton verticalButtonOverview;
    // End of variables declaration//GEN-END:variables
    
}
