/*
 * InputDescription.java
 *
 * Created on 28. September 2005, 14:42
 */

package ecobill.module.base.ui.article;

/**
 *
 * @author  Roman Georg Rädle
 */
public class InputDescription extends javax.swing.JPanel {
    
    /** Creates new form InputDescription */
    public InputDescription() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        languageL = new javax.swing.JLabel();
        language = new javax.swing.JComboBox();
        countryL = new javax.swing.JLabel();
        country = new javax.swing.JComboBox();
        variantL = new javax.swing.JLabel();
        variant = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Daten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        languageL.setText("Sprache");

        language.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        language.setToolTipText("Sprache ausw\u00e4hlen");
        language.setMinimumSize(new java.awt.Dimension(80, 20));
        language.setPreferredSize(new java.awt.Dimension(80, 20));

        countryL.setText("Land");

        country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        country.setToolTipText("Land ausw\u00e4hlen");
        country.setMinimumSize(new java.awt.Dimension(80, 20));
        country.setPreferredSize(new java.awt.Dimension(80, 20));

        variantL.setText("Dialekt");

        variant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        variant.setToolTipText("Dialekt ausw\u00e4hlen");
        variant.setMinimumSize(new java.awt.Dimension(80, 20));
        variant.setPreferredSize(new java.awt.Dimension(80, 20));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(languageL)
                    .add(language, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(countryL)
                    .add(country, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(variantL)
                    .add(variant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(languageL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(language, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(countryL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(country, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(variantL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(variant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox country;
    private javax.swing.JLabel countryL;
    private javax.swing.JComboBox language;
    private javax.swing.JLabel languageL;
    private javax.swing.JComboBox variant;
    private javax.swing.JLabel variantL;
    // End of variables declaration//GEN-END:variables
    
}
