/*
 * ArticleUIInput.java
 *
 * Created on 28. September 2005, 09:38
 */

package ecobill.module.base.ui.article;

/**
 *
 * @author  Roman Georg Rädle
 */
public class Input extends javax.swing.JPanel {
    
    /** Creates new form ArticleUIInput */
    public Input() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        articleNumberL = new javax.swing.JLabel();
        articleNumber = new javax.swing.JTextField();
        unitL = new javax.swing.JLabel();
        unit = new javax.swing.JComboBox();
        priceL = new javax.swing.JLabel();
        price = new javax.swing.JSpinner();
        inStockL = new javax.swing.JLabel();
        inStock = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Daten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        articleNumberL.setText("Artikel Nr.");

        articleNumber.setToolTipText("Artikel Nr. eingeben");

        unitL.setText("Einheit");

        unit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        unit.setToolTipText("Einheit ausw\u00e4hlen");
        unit.setMinimumSize(new java.awt.Dimension(80, 20));
        unit.setOpaque(false);
        unit.setPreferredSize(new java.awt.Dimension(80, 20));

        priceL.setText("Preis");

        price.setToolTipText("Preis eingeben");
        price.setMinimumSize(new java.awt.Dimension(80, 20));
        price.setPreferredSize(new java.awt.Dimension(80, 20));

        inStockL.setText("Lagerbestand");

        inStock.setToolTipText("Lagerbestand eingeben");
        inStock.setMinimumSize(new java.awt.Dimension(80, 20));
        inStock.setPreferredSize(new java.awt.Dimension(80, 20));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(articleNumberL)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(unit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(unitL))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(price, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(priceL))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(inStockL)
                            .add(inStock, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(articleNumber))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(articleNumberL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(articleNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(unitL)
                        .add(priceL))
                    .add(inStockL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(price, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(inStock, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(unit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField articleNumber;
    private javax.swing.JLabel articleNumberL;
    private javax.swing.JSpinner inStock;
    private javax.swing.JLabel inStockL;
    private javax.swing.JSpinner price;
    private javax.swing.JLabel priceL;
    private javax.swing.JComboBox unit;
    private javax.swing.JLabel unitL;
    // End of variables declaration//GEN-END:variables
    
}
