/*
 * DeliveryOrderArticlesDialog.java
 *
 * Created on 10. Dezember 2005, 22:47
 */

package ecobill.module.base.ui.deliveryorder;

/**
 *
 * @author  Roman Georg Rädle
 */
public class DeliveryOrderArticlesDialog extends javax.swing.JFrame {
    
    /** Creates new form DeliveryOrderArticlesDialog */
    public DeliveryOrderArticlesDialog() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        articleTable = new ecobill.module.base.ui.article.ArticleTable();
        closeB = new javax.swing.JButton();
        chooseB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        closeB.setText("Schlie\u00dfen");

        chooseB.setText("Ausw\u00e4hlen");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(articleTable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .add(chooseB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeB)
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {chooseB, closeB}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(articleTable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(closeB)
                    .add(chooseB))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryOrderArticlesDialog().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ecobill.module.base.ui.article.ArticleTable articleTable;
    private javax.swing.JButton chooseB;
    private javax.swing.JButton closeB;
    // End of variables declaration//GEN-END:variables
    
}
