/*
 * Input.java
 *
 * Created on 2. Oktober 2005, 00:41
 */

package ecobill.module.base.ui.businesspartner;

/**
 *
 * @author  Roman Georg Rädle
 */
public class Input extends javax.swing.JPanel {
    
    /** Creates new form Input */
    public Input() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        customerNumberL = new javax.swing.JLabel();
        customerNumber = new javax.swing.JTextField();
        titleL = new javax.swing.JLabel();
        title = new javax.swing.JComboBox();
        academicTitleL = new javax.swing.JLabel();
        academicTitle = new javax.swing.JComboBox();
        firstnameL = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastnameL = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        streetL = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        zipCodeL = new javax.swing.JLabel();
        zipCode = new javax.swing.JComboBox();
        cityL = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        countryL = new javax.swing.JLabel();
        country = new javax.swing.JComboBox();
        countyL = new javax.swing.JLabel();
        county = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Daten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        customerNumberL.setText("Kundennummer");

        titleL.setText("Anrede");

        title.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        title.setMinimumSize(new java.awt.Dimension(80, 20));
        title.setPreferredSize(new java.awt.Dimension(80, 20));
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });

        academicTitleL.setText("Titel");

        academicTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        academicTitle.setMinimumSize(new java.awt.Dimension(80, 20));
        academicTitle.setPreferredSize(new java.awt.Dimension(80, 20));

        firstnameL.setText("Vorname");

        firstname.setMinimumSize(new java.awt.Dimension(120, 20));
        firstname.setPreferredSize(new java.awt.Dimension(120, 20));

        lastnameL.setText("Nachname");

        lastname.setMinimumSize(new java.awt.Dimension(120, 20));
        lastname.setPreferredSize(new java.awt.Dimension(120, 20));

        streetL.setText("Stra\u00dfe");

        street.setMinimumSize(new java.awt.Dimension(120, 20));
        street.setPreferredSize(new java.awt.Dimension(120, 20));

        zipCodeL.setText("PLZ");

        zipCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        zipCode.setMinimumSize(new java.awt.Dimension(80, 20));
        zipCode.setPreferredSize(new java.awt.Dimension(80, 20));

        cityL.setText("Ort");

        city.setMinimumSize(new java.awt.Dimension(120, 20));
        city.setPreferredSize(new java.awt.Dimension(120, 20));

        countryL.setText("Land");

        country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        country.setMinimumSize(new java.awt.Dimension(120, 20));
        country.setPreferredSize(new java.awt.Dimension(120, 20));

        countyL.setText("Bundesland");

        county.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        county.setMinimumSize(new java.awt.Dimension(120, 20));
        county.setPreferredSize(new java.awt.Dimension(120, 20));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(customerNumber, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .add(customerNumberL)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(titleL)
                            .add(title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(academicTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(academicTitleL)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(firstname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .add(firstnameL))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lastnameL)
                            .add(lastname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .add(streetL)
                    .add(street, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(zipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(zipCodeL))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cityL)
                            .add(city, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(country, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .add(countryL))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(countyL)
                            .add(county, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(customerNumberL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(customerNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(titleL)
                    .add(academicTitleL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(academicTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(firstnameL)
                    .add(lastnameL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(firstname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lastname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(streetL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(street, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(zipCodeL)
                    .add(cityL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(zipCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(city, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(countryL)
                    .add(countyL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(country, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(county, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    // </editor-fold>//GEN-END:initComponents

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox academicTitle;
    private javax.swing.JLabel academicTitleL;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityL;
    private javax.swing.JComboBox country;
    private javax.swing.JLabel countryL;
    private javax.swing.JComboBox county;
    private javax.swing.JLabel countyL;
    private javax.swing.JTextField customerNumber;
    private javax.swing.JLabel customerNumberL;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel firstnameL;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel lastnameL;
    private javax.swing.JTextField street;
    private javax.swing.JLabel streetL;
    private javax.swing.JComboBox title;
    private javax.swing.JLabel titleL;
    private javax.swing.JComboBox zipCode;
    private javax.swing.JLabel zipCodeL;
    // End of variables declaration//GEN-END:variables
    
}
