# MySQL-Front 3.2  (Build 4.15)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET CHARACTER SET 'utf8' */;

# Host: localhost    Database: ecobill
# ------------------------------------------------------
# Server version 4.1.11-nt

USE `ecobill`;

#
# Dumping data for table base_banking
#

INSERT INTO `base_banking` (`ID`,`BANK_ESTABLISHMENT`,`ACCOUNT_NUMBER`,`BANK_IDENTIFICATION_NUMBER`) VALUES (1,'Sparkasse Bodensee','123456','65351050');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
