# MySQL-Front 3.2  (Build 8.0)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES latin1 */;

/*!40101 SET NAMES utf8 */;

INSERT INTO `BASE_ADDRESS` VALUES (6,'Rheingutstraße 32 / 524','78462','Konstanz','de-bw','DE');
INSERT INTO `BASE_ADDRESS` VALUES (7,'Obere Laube 51','78462','Konstanz','de-bw','DE');
INSERT INTO `BASE_ADDRESS` VALUES (8,'Breslauer Straße 53','88512','Mengen','de-bw','DE');
INSERT INTO `BASE_ADDRESS` VALUES (12,'','','',NULL,NULL);


INSERT INTO `BASE_ARTICLE` VALUES (26,'000001',1,2.95,0,5,27);
INSERT INTO `BASE_ARTICLE` VALUES (27,'000002',1,1.95,0,500,25);
INSERT INTO `BASE_ARTICLE` VALUES (28,'000003',2,0.99,150,4,24);
INSERT INTO `BASE_ARTICLE` VALUES (29,'000004',2,0.99,130,5,24);


INSERT INTO `BASE_ARTICLE_DESCRIPTION` VALUES (55,'Weizenmehl','de_DE',26);
INSERT INTO `BASE_ARTICLE_DESCRIPTION` VALUES (56,'Zucker','de_DE',27);
INSERT INTO `BASE_ARTICLE_DESCRIPTION` VALUES (57,'Kinder Pingui','de_DE',28);
INSERT INTO `BASE_ARTICLE_DESCRIPTION` VALUES (58,'Children Pingui','en_UK',28);
INSERT INTO `BASE_ARTICLE_DESCRIPTION` VALUES (59,'Milchschnitte','de_DE',29);
INSERT INTO `BASE_ARTICLE_DESCRIPTION` VALUES (60,'Milchschnittli','de_CH',29);


INSERT INTO `BASE_BANKING` VALUES (6,'','','');
INSERT INTO `BASE_BANKING` VALUES (7,'','','');
INSERT INTO `BASE_BANKING` VALUES (8,'','','');
INSERT INTO `BASE_BANKING` VALUES (12,'','','');


INSERT INTO `BASE_BILL` VALUES (1,'000001',6,'2005-11-06','bill',NULL,NULL);
INSERT INTO `BASE_BILL` VALUES (3,'000003',6,'2005-11-07','bill',NULL,NULL);
INSERT INTO `BASE_BILL` VALUES (4,'000004',7,'2005-11-08','bill',NULL,NULL);


INSERT INTO `BASE_BUSINESS_PARTNER` VALUES (6,'000001','','','',0,6,6,6);
INSERT INTO `BASE_BUSINESS_PARTNER` VALUES (7,'000002','Firma','JFucker Coorperation Ltd.','JFucking',1,7,7,7);
INSERT INTO `BASE_BUSINESS_PARTNER` VALUES (8,'000003','','','',0,8,8,8);
INSERT INTO `BASE_BUSINESS_PARTNER` VALUES (12,'000006','','','',0,12,12,12);


INSERT INTO `BASE_DELIVERY_ORDER` VALUES (1,6,'000002','2005-11-06','delivery_order','','',1,1);
INSERT INTO `BASE_DELIVERY_ORDER` VALUES (2,6,'000003','2005-11-06','delivery_order','','',1,3);
INSERT INTO `BASE_DELIVERY_ORDER` VALUES (3,6,'000004','2005-11-06','delivery_order','','',1,3);
INSERT INTO `BASE_DELIVERY_ORDER` VALUES (4,7,'000005','2005-11-07','delivery_order','','Wir danken für den lecker Einkauf.',1,4);


INSERT INTO `BASE_NUMBER_SEQUENCE` VALUES (1,'article','000004');
INSERT INTO `BASE_NUMBER_SEQUENCE` VALUES (2,'customer','000006');
INSERT INTO `BASE_NUMBER_SEQUENCE` VALUES (3,'delivery_order','000009');
INSERT INTO `BASE_NUMBER_SEQUENCE` VALUES (4,'bill','000004');


INSERT INTO `BASE_PERSON` VALUES (6,45,NULL,'Roman','Rädle','(0 75 31) 38 22 27','','roman@raedle.info',NULL);
INSERT INTO `BASE_PERSON` VALUES (7,45,48,'Sebastian','Gath','','','',NULL);
INSERT INTO `BASE_PERSON` VALUES (8,45,48,'Andreas Paul','Weiler','','','',NULL);
INSERT INTO `BASE_PERSON` VALUES (12,46,NULL,'Dicke','Omi','','','',NULL);


INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (1,'000002',0,1.95,'Sack','Zucker',1,NULL,1,10);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (2,'000002',0,1.95,'Sack','Zucker',2,NULL,1,10);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (3,'000001',0,2.95,'Sack','Weizenmehl',3,NULL,1,50);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (4,'000002',0,1.95,'Sack','Zucker',4,NULL,1,10);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (5,'000003',0,0.99,'Stück','Kinder Pingui',4,NULL,2,50);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (6,'000001',0,2.95,'Sack','Weizenmehl',4,NULL,3,30);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (7,'000003',0,0.99,'Stück','Kinder Pingui',NULL,NULL,1,10);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (8,'000002',0,1.95,'Sack','Zucker',NULL,NULL,2,20);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (9,'000003',0,0.99,'Stück','Kinder Pingui',NULL,NULL,1,30);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (10,'000002',0,1.95,'Sack','Zucker',NULL,NULL,2,20);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (11,'000004',0,0.99,'Stück','Milchschnitte',NULL,NULL,1,10);
INSERT INTO `BASE_REDUPLICATED_ARTICLE` VALUES (12,'000002',0,1.95,'Sack','Zucker',NULL,NULL,1,10);


INSERT INTO `BASE_SYSTEM_COUNTRY` VALUES (1,'DE','de');
INSERT INTO `BASE_SYSTEM_COUNTRY` VALUES (2,'AT','de');
INSERT INTO `BASE_SYSTEM_COUNTRY` VALUES (3,'CH','de');
INSERT INTO `BASE_SYSTEM_COUNTRY` VALUES (4,'UK','en');
INSERT INTO `BASE_SYSTEM_COUNTRY` VALUES (5,'US','en');


INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (1,'de-bw','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (2,'de-by','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (3,'de-be','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (4,'de-br','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (5,'de-hb','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (6,'de-hh','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (7,'de-he','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (8,'de-mv','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (9,'de-ni','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (10,'de-nw','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (11,'de-rp','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (12,'de-sl','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (13,'de-sn','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (14,'de-st','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (15,'de-sh','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (16,'de-th','DE');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (17,'at-1','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (18,'at-2','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (19,'at-3','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (20,'at-4','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (21,'at-5','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (22,'at-6','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (23,'at-7','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (24,'at-8','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (25,'at-9','AT');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (26,'ch-zh','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (27,'ch-be','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (29,'ch-lu','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (30,'ch-ur','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (31,'ch-sz','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (32,'ch-ow','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (33,'ch-nw','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (34,'ch-gl','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (35,'ch-zg','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (36,'ch-fr','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (37,'ch-so','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (38,'ch-bs','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (39,'ch-bl','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (40,'ch-sh','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (41,'ch-ar','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (42,'ch-ai','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (43,'ch-sg','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (44,'ch-gr','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (45,'ch-ag','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (46,'ch-tg','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (47,'ch-ti','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (48,'ch-vd','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (49,'ch-vs','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (50,'ch-ne','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (51,'ch-ge','CH');
INSERT INTO `BASE_SYSTEM_COUNTY` VALUES (52,'ch-ju','CH');


INSERT INTO `BASE_SYSTEM_LANGUAGE` VALUES (1,'de');
INSERT INTO `BASE_SYSTEM_LANGUAGE` VALUES (2,'en');


INSERT INTO `BASE_SYSTEM_LOCALE` VALUES (1,'de_DE','','de','DE');
INSERT INTO `BASE_SYSTEM_LOCALE` VALUES (2,'de_AT','','de','AT');
INSERT INTO `BASE_SYSTEM_LOCALE` VALUES (3,'de_CH','','de','CH');
INSERT INTO `BASE_SYSTEM_LOCALE` VALUES (4,'en_UK','','en','UK');
INSERT INTO `BASE_SYSTEM_LOCALE` VALUES (5,'en_US','','en','US');


INSERT INTO `BASE_SYSTEM_MESSAGE` VALUES (1,'Roman','Test','Testnachricht');


INSERT INTO `BASE_SYSTEM_UNIT` VALUES (1,'amount.bag','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (2,'amount.piece','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (3,'weight.mg','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (4,'weight.g','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (5,'weight.kg','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (6,'weight.t','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (7,'volume.ml','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (8,'volume.cl','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (9,'volume.l','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (10,'scale.mm','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (11,'scale.cm','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (12,'scale.dm','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (13,'scale.m','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (14,'scale.km','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (15,'scale.mm_quad','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (16,'scale.cm_quad','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (17,'scale.dm_quad','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (18,'scale.m_quad','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (19,'scale.km_quad','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (20,'scale.ar','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (21,'scale.hekta','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (22,'scale.morgen','unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (23,'amount.bag','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (24,'amount.piece','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (25,'weight.mg','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (26,'weight.g','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (27,'weight.kg','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (28,'weight.t','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (29,'volume.ml','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (30,'volume.cl','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (31,'volume.l','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (32,'scale.mm','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (33,'scale.cm','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (34,'scale.dm','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (35,'scale.m','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (36,'scale.km','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (37,'scale.mm_quad','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (38,'scale.cm_quad','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (39,'scale.dm_quad','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (40,'scale.m_quad','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (41,'scale.km_quad','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (42,'scale.ar','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (43,'scale.hekta','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (44,'scale.morgen','bundle_unit');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (45,'mr','title');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (46,'mrs','title');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (47,'dr','academic_title');
INSERT INTO `BASE_SYSTEM_UNIT` VALUES (48,'prof_dr','academic_title');

/*!40101 SET NAMES latin1 */;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
