alter table BASE_ARTICLE drop constraint FK7FD39D68E5FDBA65;
alter table BASE_ARTICLE drop constraint FK7FD39D68DAFE8522;
alter table BASE_ARTICLE_DESCRIPTION drop constraint FK90003785FBC7C981;
alter table BASE_BILL drop constraint FK3B8E70B592A54740;
alter table BASE_BUSINESS_PARTNER drop constraint FK2BB6BED7B6A22533;
alter table BASE_BUSINESS_PARTNER drop constraint FK2BB6BED733F5BB81;
alter table BASE_BUSINESS_PARTNER drop constraint FK2BB6BED7292080C1;
alter table BASE_DELIVERY_ORDER drop constraint FK98DB0A5192A54740;
alter table BASE_DELIVERY_ORDER drop constraint FK98DB0A51CBBF2233;
alter table BASE_PERSON drop constraint FKA96370837F16C806;
alter table BASE_PERSON drop constraint FKA96370837C9C9BCE;
alter table BASE_PERSON drop constraint FKA9637083292080C1;
alter table BASE_REDUPLICATED_ARTICLE drop constraint FK41BAB371A0761D98;
drop table BASE_ADDRESS if exists;
drop table BASE_ARTICLE if exists;
drop table BASE_ARTICLE_DESCRIPTION if exists;
drop table BASE_BANKING if exists;
drop table BASE_BILL if exists;
drop table BASE_BUSINESS_PARTNER if exists;
drop table BASE_DELIVERY_ORDER if exists;
drop table BASE_NUMBER_SEQUENCE if exists;
drop table BASE_PERSON if exists;
drop table BASE_REDUPLICATED_ARTICLE if exists;
drop table BASE_SYSTEM_COUNTRY if exists;
drop table BASE_SYSTEM_COUNTY if exists;
drop table BASE_SYSTEM_LANGUAGE if exists;
drop table BASE_SYSTEM_LOCALE if exists;
drop table BASE_SYSTEM_MESSAGE if exists;
drop table BASE_SYSTEM_TEXT_BLOCK if exists;
drop table BASE_SYSTEM_UNIT if exists;
create table BASE_ADDRESS (
    ID bigint generated by default as identity (start with 1),
    STREET varchar(255) not null,
    ZIP_CODE varchar(255) not null,
    CITY varchar(255) not null,
    COUNTRY_KEY varchar(255),
    COUNTY_KEY varchar(255),
    primary key (ID)
);
create table BASE_ARTICLE (
    ID bigint generated by default as identity (start with 1),
    ARTICLE_NUMBER varchar(255) not null,
    UNIT_ID bigint,
    PRICE double not null,
    IN_STOCK double not null,
    BUNDLE_CAPACITY double,
    BUNDLE_UNIT_ID bigint,
    primary key (ID),
    unique (ARTICLE_NUMBER)
);
create table BASE_ARTICLE_DESCRIPTION (
    ID bigint generated by default as identity (start with 1),
    DESCRIPTION varchar(4000) not null,
    SYSTEM_LOCALE_KEY varchar(255),
    ARTICLE_ID bigint,
    primary key (ID)
);
create table BASE_BANKING (
    ID bigint generated by default as identity (start with 1),
    BANK_ESTABLISHMENT varchar(255) not null,
    ACCOUNT_NUMBER varchar(255) not null,
    BANK_IDENTIFICATION_NUMBER varchar(255) not null,
    primary key (ID)
);
create table BASE_BILL (
    ID bigint generated by default as identity (start with 1),
    BUSINESS_PARTNER_ID bigint,
    BILL_NUMBER varchar(255) not null,
    BILL_DATE date not null,
    CHARACTERISATION_TYPE varchar(255),
    PREFIX_FREE_TEXT varchar(4000),
    SUFFIX_FREE_TEXT varchar(4000),
    primary key (ID)
);
create table BASE_BUSINESS_PARTNER (
    ID bigint generated by default as identity (start with 1),
    CUSTOMER_NUMBER varchar(255) not null,
    COMPANY_TITLE varchar(255),
    COMPANY_NAME varchar(255),
    COMPANY_BRANCH varchar(255),
    FOR_ATTENTION_OF bit not null,
    PERSON_ID bigint,
    ADDRESS_ID bigint,
    BANKING_ID bigint,
    primary key (ID),
    unique (CUSTOMER_NUMBER)
);
create table BASE_DELIVERY_ORDER (
    ID bigint generated by default as identity (start with 1),
    BUSINESS_PARTNER_ID bigint,
    DELIVERY_ORDER_NUMBER varchar(255) not null,
    DELIVERY_ORDER_DATE date not null,
    CHARACTERISATION_TYPE varchar(255) not null,
    PREFIX_FREE_TEXT varchar(4000),
    SUFFIX_FREE_TEXT varchar(4000),
    PREPARED_BILL bit not null,
    BILL_ID bigint,
    primary key (ID),
    unique (DELIVERY_ORDER_NUMBER)
);
create table BASE_NUMBER_SEQUENCE (
    ID bigint generated by default as identity (start with 1),
    SEQUENCE_KEY varchar(255) not null,
    NUMBER varchar(255) not null,
    primary key (ID)
);
create table BASE_PERSON (
    ID bigint generated by default as identity (start with 1),
    TITLE_ID bigint,
    ACADEMIC_TITLE_ID bigint,
    FIRSTNAME varchar(255),
    LASTNAME varchar(255),
    PHONE varchar(255),
    FAX varchar(255),
    EMAIL varchar(255),
    ADDRESS_ID bigint,
    primary key (ID)
);
create table BASE_REDUPLICATED_ARTICLE (
    ID bigint generated by default as identity (start with 1),
    DELIVERY_ORDER_ID bigint,
    ORDER_POSITION integer not null,
    ARTICLE_NUMBER varchar(255),
    QUANTITY double not null,
    UNIT varchar(255) not null,
    PRICE double not null,
    DESCRIPTION varchar(4000) not null,
    primary key (ID)
);
create table BASE_SYSTEM_COUNTRY (
    ID bigint generated by default as identity (start with 1),
    SYSTEM_COUNTRY_KEY varchar(255) not null,
    SYSTEM_LANGUAGE_KEY varchar(255),
    primary key (ID),
    unique (SYSTEM_COUNTRY_KEY)
);
create table BASE_SYSTEM_COUNTY (
    ID bigint generated by default as identity (start with 1),
    SYSTEM_COUNTY_KEY varchar(255) not null,
    SYSTEM_COUNTRY_KEY varchar(255),
    primary key (ID),
    unique (SYSTEM_COUNTY_KEY)
);
create table BASE_SYSTEM_LANGUAGE (
    ID bigint generated by default as identity (start with 1),
    SYSTEM_LANGUAGE_KEY varchar(255) not null,
    primary key (ID),
    unique (SYSTEM_LANGUAGE_KEY)
);
create table BASE_SYSTEM_LOCALE (
    ID bigint generated by default as identity (start with 1),
    SYSTEM_LOCALE_KEY varchar(255) not null,
    SYSTEM_LANGUAGE_KEY varchar(255) not null,
    SYSTEM_COUNTRY_KEY varchar(255) not null,
    VARIANT varchar(255),
    primary key (ID),
    unique (SYSTEM_LOCALE_KEY)
);
create table BASE_SYSTEM_MESSAGE (
    ID bigint generated by default as identity (start with 1),
    ADDRESSER varchar(255) not null,
    SUBJECT varchar(255) not null,
    MESSAGE varchar(255) not null,
    primary key (ID)
);
create table BASE_SYSTEM_TEXT_BLOCK (
    ID bigint generated by default as identity (start with 1),
    TEXT_BLOCK_NAME varchar(200),
    TEXT_BLOCK_TEXT varchar(4000),
    primary key (ID)
);
create table BASE_SYSTEM_UNIT (
    ID bigint generated by default as identity (start with 1),
    UNIT_KEY varchar(255) not null,
    CATEGORY varchar(255) not null,
    primary key (ID)
);
alter table BASE_ARTICLE 
    add constraint FK7FD39D68E5FDBA65 
    foreign key (BUNDLE_UNIT_ID) 
    references BASE_SYSTEM_UNIT;
alter table BASE_ARTICLE 
    add constraint FK7FD39D68DAFE8522 
    foreign key (UNIT_ID) 
    references BASE_SYSTEM_UNIT;
alter table BASE_ARTICLE_DESCRIPTION 
    add constraint FK90003785FBC7C981 
    foreign key (ARTICLE_ID) 
    references BASE_ARTICLE;
alter table BASE_BILL 
    add constraint FK3B8E70B592A54740 
    foreign key (BUSINESS_PARTNER_ID) 
    references BASE_BUSINESS_PARTNER;
alter table BASE_BUSINESS_PARTNER 
    add constraint FK2BB6BED7B6A22533 
    foreign key (PERSON_ID) 
    references BASE_PERSON;
alter table BASE_BUSINESS_PARTNER 
    add constraint FK2BB6BED733F5BB81 
    foreign key (BANKING_ID) 
    references BASE_BANKING;
alter table BASE_BUSINESS_PARTNER 
    add constraint FK2BB6BED7292080C1 
    foreign key (ADDRESS_ID) 
    references BASE_ADDRESS;
alter table BASE_DELIVERY_ORDER 
    add constraint FK98DB0A5192A54740 
    foreign key (BUSINESS_PARTNER_ID) 
    references BASE_BUSINESS_PARTNER;
alter table BASE_DELIVERY_ORDER 
    add constraint FK98DB0A51CBBF2233 
    foreign key (BILL_ID) 
    references BASE_BILL;
alter table BASE_PERSON 
    add constraint FKA96370837F16C806 
    foreign key (ACADEMIC_TITLE_ID) 
    references BASE_SYSTEM_UNIT;
alter table BASE_PERSON 
    add constraint FKA96370837C9C9BCE 
    foreign key (TITLE_ID) 
    references BASE_SYSTEM_UNIT;
alter table BASE_PERSON 
    add constraint FKA9637083292080C1 
    foreign key (ADDRESS_ID) 
    references BASE_ADDRESS;
alter table BASE_REDUPLICATED_ARTICLE 
    add constraint FK41BAB371A0761D98 
    foreign key (DELIVERY_ORDER_ID) 
    references BASE_DELIVERY_ORDER;
