/*
 * InputContact.java
 *
 * Created on 2. Oktober 2005, 01:03
 */

package ecobill.module.base.ui.businesspartner;

/**
 *
 * @author  Roman Georg Rädle
 */
public class InputContact extends javax.swing.JPanel {
    
    /** Creates new form InputContact */
    public InputContact() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        phoneL = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        faxL = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();
        emailL = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Kontakt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        phoneL.setText("Telefon");

        phone.setMinimumSize(new java.awt.Dimension(120, 20));
        phone.setPreferredSize(new java.awt.Dimension(120, 20));

        faxL.setText("Telefax");

        fax.setMinimumSize(new java.awt.Dimension(120, 20));
        fax.setPreferredSize(new java.awt.Dimension(120, 20));

        emailL.setText("E-Mail");

        email.setMinimumSize(new java.awt.Dimension(120, 20));
        email.setPreferredSize(new java.awt.Dimension(120, 20));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(phoneL)
                    .add(phone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .add(faxL)
                    .add(fax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .add(emailL)
                    .add(email, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(phoneL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(phone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(faxL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField fax;
    private javax.swing.JLabel faxL;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneL;
    // End of variables declaration//GEN-END:variables
    
}
